rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-19mode
  - ruby-head
  # - rbx

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email:
    on_success: change # only send if status changes
