rvm:
  - 1.9.3
  - 2.1.7
  - 2.2.3
  - jruby-19mode
  - ruby-head
  - rbx

before_install:
  - gem update bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx

notifications:
  email:
    on_success: change # only send if status changes
